name:  simple_features
description:  An implementation of the Simple Features specification for Dart
author: Karl Guggisberg <karl.guggisberg@guggis.ch>
version: 0.0.1

dependencies:
  unittest: any
  meta: any
