name:  simple_features
description:  An implementation of the Simple Features Specification for Dart
author: Karl Guggisberg <karl.guggisberg@guggis.ch>
version: 0.0.1+3
homepage: https://github.com/Gubaer/dart-simple-features.git
documentation: http://gubaer.github.io/dart-simple-features/doc/index.html

dependencies:
   meta: ">=0.5.0+1 <0.5.1"

dev_dependencies:
  unittest: ">=0.5.0+1 <0.5.1"

